site_name: OSG Virtual School 2021
site_url: https://opensciencegrid.org/virtual-school-2021
repo_name: null
theme:
  name: material

nav:
  - Home:                    index.md
  - Schedule:                schedule.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - toc:
      permalink: True
  - pymdownx.caret  # superscripts
